{
 "title": "Single Job Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "JobID", "label": "Slurm JobID" },
   {
    "name": "node",
    "label": "Nodes",
    "query": {
     "query": "cgroup_cpus{cgroup=\"/slurm_localhost/uid_0/job_$JobID\", instance=\"localhost:9306\", job=\"prometheus\"}"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1m,2m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Slurm Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Job Total CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(irate(cgroup_cpu_user_seconds{cgroup=\"/slurm_localhost/uid_0/job_$JobID\", instance=\"localhost:9306\", job=\"prometheus\"}[5m]) / cgroup_cpus{cgroup=\"/slurm_localhost/uid_0/job_$JobID\", instance=\"localhost:9306\", job=\"prometheus\"}, \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "User on {{shostname}}"
    },
    {
     "expr": "label_replace(irate(cgroup_cpu_system_seconds{cgroup=\"/slurm_localhost/uid_0/job_$JobID\", instance=\"localhost:9306\", job=\"prometheus\"}[5m]) / cgroup_cpus{cgroup=\"/slurm_localhost/uid_0/job_$JobID\", instance=\"localhost:9306\", job=\"prometheus\"}, \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "System on {{shostname}}"
    },
    {
     "expr": "label_replace(irate(cgroup_cpu_total_seconds{cgroup=\"/slurm_localhost/uid_0/job_$JobID\", instance=\"localhost:9306\", job=\"prometheus\"}[5m]) / cgroup_cpus{cgroup=\"/slurm_localhost/uid_0/job_$JobID\", instance=\"localhost:9306\", job=\"prometheus\"},  \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "Total on {{shostname}}"
    }
   ]
  },
  {
   "title": "Job CPU Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(cgroup_memory_total_bytes{cgroup=\"/slurm_localhost/uid_0/job_$JobID\", instance=\"localhost:9306\", job=\"prometheus\"}, \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "Total allocated {{shostname}}"
    },
    {
     "expr": "label_replace(cgroup_memory_rss_bytes{cgroup=\"/slurm_localhost/uid_0/job_$JobID\", instance=\"localhost:9306\", job=\"prometheus\"}, \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "Rss {{shostname}}"
    },
    {
     "expr": "label_replace(cgroup_memory_cache_bytes{cgroup=\"/slurm_localhost/uid_0/job_$JobID\", instance=\"localhost:9306\", job=\"prometheus\"}, \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "Cache  {{shostname}}"
    },
    {
     "expr": "label_replace(cgroup_memory_used_bytes{cgroup=\"/slurm_localhost/uid_0/job_$JobID\", instance=\"localhost:9306\", job=\"prometheus\"}, \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "Used  {{shostname}}"
    },
    {
     "expr": "label_replace(irate(cgroup_memory_fail_count{cgroup=\"/slurm_localhost/uid_0/job_$JobID\", instance=\"localhost:9306\", job=\"prometheus\"}[$interval]), \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "Failures {{shostname}}"
    }
   ]
  },
  {
   "title": "GPU Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "GPU Utilization",
     "type": "timeseries",
     "description": "GPU Utilization",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "label_replace(nvidia_gpu_duty_cycle and nvidia_gpu_jobId == $JobID, \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
       "legendFormat": "{{shostname}} GPU {{minor_number}}"
      }
     ]
    },
    {
     "title": "GPU Memory utilization",
     "type": "timeseries",
     "description": "GPU Memory Utilization",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(nvidia_gpu_memory_used_bytes and nvidia_gpu_jobId == $JobID, \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
       "legendFormat": "{{shostname}} GPU {{minor_number}}"
      }
     ]
    },
    {
     "title": "GPU Temperature",
     "type": "timeseries",
     "description": "GPU Temperature",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "label_replace(nvidia_gpu_temperature_celsius and nvidia_gpu_jobId == $JobID, \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
       "legendFormat": "{{shostname}} GPU {{minor_number}}"
      }
     ]
    },
    {
     "title": "GPU Power Usage",
     "type": "timeseries",
     "description": "GPU Power Usage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "mwatt" } },
     "targets": [
      {
       "expr": "label_replace(nvidia_gpu_power_usage_milliwatts and nvidia_gpu_jobId == $JobID, \"shostname\", \"$1\", \"instance\", \"(.*):.*\")",
       "legendFormat": "{{shostname}} GPU {{minor_number}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Stat for $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "node",
   "targets": [
    {}
   ]
  },
  {
   "title": "Node $node CPU Percentage Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"$node:9100\",mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"$node:9100\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=\"$node:9100\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "IO-Wait"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=\"$node:9100\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Node $node Total Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node:9100\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node:9100\"} - node_memory_MemAvailable_bytes{instance=\"$node:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"$node:9100\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$node:9100\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node:9100\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node:9100\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Local Disc R/W for $node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$node:9100\"}[$interval])",
     "legendFormat": "{{device}}_Read bytes"
    },
    {
     "expr": "rate(node_disk_write_bytes_total{instance=\"$node:9100\"}[$interval])",
     "legendFormat": "{{device}}_Write bytes"
    }
   ]
  },
  {
   "title": "Local Disc IOPS for $node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=\"$node:9100\"}[$interval])",
     "legendFormat": "{{device}}_Reads"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=\"$node:9100\"}[$interval])",
     "legendFormat": "{{device}}_Writes"
    }
   ]
  }
 ]
}